baseURL = 'https://zmfpdl64.github.io/'
languageCode = 'ko-kr'
title = '블로그 제목'
theme = 'PaperMod'
paginate = 10

[params]
  author = '이름'
  description = '설명'
  ShowBreadCrumbs = true
  ShowReadingTime = true
  ShowShareButtons = true
  ShowPostNavLinks = true
  ShowCodeCopyButtons = true
